# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 16:07
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0002_auto_20171023_1119'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='marker',
            managers=[
                ('ctype', django.db.models.manager.Manager()),
            ],
        ),
    ]
