# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 22:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0003_auto_20171129_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='create_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='markers_marker_create_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
