# Generated by Django 2.0.2 on 2018-02-20 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0005_auto_20171215_1600'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='marker',
            managers=[
            ],
        ),
    ]
